spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_schema?useSSL=false
    username: user
    password: 12345
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true